---
- name: Create directory for external disk
  file:
    path: /mmt/ext
    state: directory

- name: Mount external disk
  mount:
    path: /mnt/ext
    src: /dev/sda1
    fstype: xfs
    state: mounted
