---
- hosts: all
  remote_user: pi
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: dist

    - name: Install packages
      apt:
        name:
          - python3-pip
          - python3-venv
          - jq
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - exfat-fuse
          - exfat-utils
          - telnet
          - ufw
          - vim
        state: present

    - name: Setup docker
      include_role:
        name: docker
      tags:
        - docker

    - name: Create directory for external disk
      file:
        path: /media/exfat
        state: directory
      tags:
        - disk

    - name: Mount external disk
      mount:
        path: /media/exfat
        src: /dev/sda1
        fstype: exfat
        state: mounted
      tags:
        - disk

    - name: Extract node_exporter
      unarchive:
        src: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-armv7.tar.gz
        dest: /home/pi
        remote_src: yes
      tags:
        - monitoring

    - name: Copy node_exporter to sbin
      copy:
        src: /home/pi/node_exporter-0.18.1.linux-armv7/node_exporter
        dest: /usr/sbin/node_exporter
        remote_src: yes
        mode: 0755
      tags:
        - monitoring

    - name: Make service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter

          [Service]
          EnvironmentFile=/etc/default/node_exporter
          ExecStart=/usr/sbin/node_exporter $OPTIONS

          [Install]
          WantedBy=multi-user.target
      tags:
        - monitoring

    - name: Create service options
      copy:
        dest: /etc/default/node_exporter
        content: |
          OPTIONS=""
      tags:
        - monitoring

    - name: Start node_exporter service
      service:
        name: node_exporter
        state: started
      tags:
        - monitoring
