---
- hosts: all
  remote_user: pi
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: dist

    - name: Install packages
      apt:
        name:
          - python3-pip
          - python3-venv
          - jq
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - curl
          - vim
        state: present
        install_recommends: no

    - name: Setup docker
      include_role:
        name: docker
      tags:
        - docker
