---
- hosts: all
  remote_user: pi
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: dist

    - name: Install packages
      apt:
        name:
          - python3-pip
          - python3-venv
          - jq
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - exfat-fuse
          - exfat-utils
          - telnet
          - ufw
          - vim
        state: present

    - name: Setup docker
      include_role:
        name: docker
      tags:
        - docker

    - name: Mount external disk
      include_role:
        name: disk
      tags:
        - disk

    - name: Setup prometheus node_exporter
      include_role:
        name: monitoring
      tags:
        - monitoring
