---
- hosts: all
  remote_user: pi
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: dist

    - name: Install packages
      apt:
        name:
          - python3-pip
          - python3-venv
          - jq
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - exfat-fuse
          - exfat-utils
          - telnet
          - ufw
          - vim
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
      tags:
        - docker

    - name: Add Docker APT repository
      apt_repository:
        repo: >
           deb [arch=armhf]
           https://download.docker.com/linux/debian
           {{ ansible_distribution_release }} stable
      tags:
        - docker

    - name: Install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
        state: present
      tags:
        - docker

    - name: Add user to group docker
      user:
        groups:
          - docker
        append: yes
        name: "{{ ansible_user }}"
      tags:
        - docker

    - name: Create directory for external disk
      file:
        path: /media/exfat
        state: directory
      tags:
        - disk

    - name: Mount external disk
      mount:
        path: /media/exfat
        src: /dev/sda1
        fstype: exfat
        state: mounted
      tags:
        - disk

    - name: Extract node_exporter
      unarchive:
        src: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-armv7.tar.gz
        dest: /home/pi
        remote_src: yes
      tags:
        - monitoring

    - name: Copy node_exporter to sbin
      copy:
        src: /home/pi/node_exporter-0.18.1.linux-armv7/node_exporter
        dest: /usr/sbin/node_exporter
        remote_src: yes
        mode: 0755
      tags:
        - monitoring

    - name: Make service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter

          [Service]
          EnvironmentFile=/etc/default/node_exporter
          ExecStart=/usr/sbin/node_exporter $OPTIONS

          [Install]
          WantedBy=multi-user.target
      tags:
        - monitoring

    - name: Create service options
      copy:
        dest: /etc/default/node_exporter
        content: |
          OPTIONS=""
      tags:
        - monitoring

    - name: Start node_exporter service
      service:
        name: node_exporter
        state: started
      tags:
        - monitoring
