---
- name: Extract node_exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-armv7.tar.gz
    dest: /home/pi
    remote_src: yes

- name: Copy node_exporter to sbin
  copy:
    src: /home/pi/node_exporter-0.18.1.linux-armv7/node_exporter
    dest: /usr/sbin/node_exporter
    remote_src: yes
    mode: 0755

- name: Make service
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter

      [Service]
      EnvironmentFile=/etc/default/node_exporter
      ExecStart=/usr/sbin/node_exporter $OPTIONS

      [Install]
      WantedBy=multi-user.target

- name: Create service options
  copy:
    dest: /etc/default/node_exporter
    content: |
      OPTIONS=""

- name: Start node_exporter service
  service:
    name: node_exporter
    state: started
